### ISSUE TITLE
T12: Fetch Categories

### ISSUE THREAD

**Issue by oztrkmrt** [oztrkmrt/E-Commerce#14]
- [x] Fetch categories by **thunk action** and store it in the `gobal reducer`
- [x] endpoint `/categories`
- [x] list categories on the screen
- [x] categories should be link
- [x] on click it should navigate to `/shop/:gender/:category`   
samples: 
`shop/kadin/ayakkabi`
`shop/erkek/gomlek`
- [x] top 5 categories should be listed on the screen with images regarding `rating` value
- [x] all categories should be listed in drop down menu on header
- [x] Drop down menu should be in the same format as below:

![Image](https://github.com/user-attachments/assets/46c61909-bd48-471a-8585-7e3cbc1daff1)

**Comment by gokhanozdemir** [comment]
- [ ] Kategorileri çözemezsen Slackten yaz.
